[package]
name = "firechicken-club"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6"
chrono = { version = "0.4.31", default-features = false, features = ["std", "serde"] }
lazy_static = "1"
maud = { version = "0.25.0", features = ["axum"] }
serde = { version = "1", features = ["derive"], default-features = false }
shuttle-axum = "0.32.0"
shuttle-runtime = "0.32.0"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml = "0.8"
tower-http = { version = "0.4", features = ["fs"] }
tracing = "0.1"
url = { version = "2.4.1", features = ["serde"] }
