[[members]]
slug = "arne"
name = "Arne Bahlo"
url = "https://arne.me"
joined = "2023-11-12"
rss_feeds = [
  { title = "Arne Bahlo", xml_url = "https://arne.me/articles/atom.xml", html_url = "https://arne.me/articles"},
  { title = "Arne’s Weekly", xml_url = "https://arne.me/weekly/atom.xml", html_url = "https://arne.me/weekly"},
  { title = "Arne Bahlo’s Book Reviews", xml_url ="https://arne.me/book-reviews/feed.xml", html_url = "https://arne.me/book-reviews" }
]

[[members]]
slug = "ollie"
name = "ollie"
url = "https://flbn.sh"
joined = "2023-11-13"

[[members]]
slug = "lukas"
name = "Lukas Malkmus"
url = "https://lukasmalkmus.com"
joined = "2023-11-13"

[[members]]
slug = "pwa"
name = "Philipp Waldhauer"
url = "https://knuspermagier.de"
joined = "2023-11-13"
rss_feeds = [{ xml_url = "https://knuspermagier.de/feed" }]

[[members]]
slug = "kotatsuyaki"
name = "kotatsuyaki"
url = "https://blog.kotatsu.dev"
joined = "2023-11-15"
rss_feeds = [
  { xml_url = "https://blog.kotatsu.dev/feed.xml" },
  { title = "kotatsuyaki’s notes", xml_url = "https://blog.kotatsu.dev/notes.xml", html_url = "https://blog.kotatsu.dev/notes" }
]

[[members]]
slug = "cv"
name = "Christoph Voigt"
url = "https://christophvoigt.com"
joined = "2023-11-15"
rss_feeds = [{ xml_url =  "https://christophvoigt.com/rss.xml" }]

[[members]]
slug = "igor"
name = "Igor Bedesqui"
url = "https://igorbedesqui.com"
joined = "2023-11-20"

[[members]]
slug = "hexedit"
name = "HexEdit Reality"
url = "https://hexeditreality.com/"
joined = "2023-11-24"
rss_feeds = [
  { xml_url = "https://hexeditreality.com/index.xml" }
]

[[members]]
slug = "stefan"
name = "Stefan Kühnel"
url = "https://stefankuehnel.com"
joined = "2023-11-27"

[[members]]
slug = "dan"
name = "Dan Newman"
url = "https://dan.newman.is"
joined = "2023-12-13"
