[[members]]
slug = "arne"
name = "Arne Bahlo"
url = "https://arne.me"
joined = "2023-11-12"

[[members]]
slug = "ollie"
name = "ollie"
url = "https://flbn.sh"
joined = "2023-11-13"

[[members]]
slug = "lukas"
name = "Lukas Malkmus"
url = "https://lukasmalkmus.com"
joined = "2023-11-13"

[[members]]
slug = "pwa"
name = "Philipp Waldhauer"
url = "https://knuspermagier.de"
joined = "2023-11-13"
